### ISSUE TITLE
Dragon Burner Doesn't Have Full Travel in Y-axis

### ISSUE THREAD

**Issue by Nyshan** [waytotheweb/voron#1]
I know that this is noted as an issue in the readme but I think a possible solution would be to use 3mm FHCS screws and bevel the internal edge of the top two screw holes in the HE-Fan.

**Comment by waytotheweb** [comment]
I've developed a screwless way of attaching the fan which overcomes the issue entirely. I'll publish the new cowls in the next couple of days as I'm also looking into adding Klicky support too.

**Comment by waytotheweb** [comment]
Closing this now as the 3010 fan buds hold the hotend fan without the need for screws.
