### ISSUE TITLE
What do I print for the dragon Ultra high flow variant?

### ISSUE THREAD

**Issue by AikoKiss** [waytotheweb/voron#5]
I'm very confused as to which option is for the dragon, and I'm also using a dragon v2 with volcano Tblock, any help would be appreciated, thank you!

**Comment by waytotheweb** [comment]
For the Dragon UHF (with the extender), you would want to use the [Rapid Burner](https://github.com/waytotheweb/voron/tree/main/V0/Rapid_Burner)

**Comment by AikoKiss** [comment]
I printed the rapid burmer cowel, but theeres 2 different variant, normal and hf, what's the HF one for?

**Comment by waytotheweb** [comment]
HF is for the standard length Rapido, or the Dragon UHF without the extender on.
