### ISSUE TITLE
hi!, I'd like  request something

### ISSUE THREAD

**Issue by AikoKiss** [waytotheweb/voron#7]
is it possible for you to make a hf version but with support for zero click?

**Comment by AikoKiss** [comment]
I have a dragon v2 with a volcano t6 block and I havent been able to find anything that supports it, I'm also pairing it with zeroclick but the cowl for hf happens to not support zeroclick

**Comment by waytotheweb** [comment]
I've uploaded a RapidBurner HF ZeroClick cowl for you:
https://github.com/waytotheweb/voron/blob/main/V0/Rapid_Burner/STLs/HF/Cowl_ZeroClick.stl

**Comment by AikoKiss** [comment]
Thank you so much! 💓  me and a buddy also did the same thing, fusion didnt act nicely though!, ur awsome!
