### ISSUE TITLE
Do I mount the hotend with the heater cartiage facing forward or the tempeture sensor side?

### ISSUE THREAD

**Issue by AikoKiss** [waytotheweb/voron#8]
I don't know which direction to mount the hotend pls help ;(

**Comment by AikoKiss** [comment]
oh and the hotend is a dragon high flow with volcano t block!

**Comment by waytotheweb** [comment]
You mount it with the heater cartridge at the back (looking from the front of the toolhead) and the thermistor at the front with the wire following the 3010 hotend fan out the back

**Comment by AikoKiss** [comment]
awsome, thank you <3
